name: API
on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/api/**/*.*'

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    continue-on-error: false

    defaults:
      run:
        working-directory: projects/api

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_WEB_URL: ${{ secrets.WEB_URL }}
          envkey_RP_ID: ${{ secrets.RP_ID }}
          directory: projects/api/
          file_name: 'env'

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: passkey-demo-api # the name of the project on Deno Deploy
          entrypoint: dev.ts # the entrypoint to deploy
          root: projects/api
          import-map: deno.json