name: WEB
on:
  workflow_dispatch:
  push:

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    continue-on-error: false

    defaults:
      run:
        working-directory: projects/web

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          directory: projects/web
          file_name: 'env'

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate build
        run: deno task build

      - name: Remove node_modules
        run: |
          rm -rf ./node_modules ./src

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: passkey-demo # the name of the project on Deno Deploy
          entrypoint: main.ts # the entrypoint to deploy
          root: projects/web
          import-map: deno.json